apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-ui
  labels:
    app: streamlit-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-ui
  template:
    metadata:
      labels:
        app: streamlit-ui
    spec:
      serviceAccountName: gke-turns-10-ksa
      containers:
      - name: ui
        image: us-central1-docker.pkg.dev/gke-turns-10-hackathon-2600/gke-turns-10-repo/streamlit-ui:v1
        ports:
        - containerPort: 8501
        env:
        - name: MCP_SERVER_URL
          value: "http://mcp-server-service.default.svc.cluster.local:8080"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app: streamlit-ui
spec:
  type: LoadBalancer
  selector:
    app: streamlit-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
